# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - matcha_nginx_data:/data

  ui:
    command: yarn start
    mem_limit: 1g
    stdin_open: true
    volumes:
      - ./ui:/app #Allows source folders to be watched

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server/src:/app/src # Allows source folders to be watched
      - ./server/config:/app/config
      - matcha_server_data:/data
    environment:
      - MATCHA_ENV=local
      - MATCHA_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - matcha_mongodb_data:/data

  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - matcha_data_elasticsearch:/usr/share/elasticsearch/data:z

volumes:
  matcha_mongodb_data:
    driver: local
    name: matcha_mongodb_data
  matcha_nginx_data:
    driver: local
    name: matcha_nginx_data
  matcha_server_data:
    driver: local
    name: matcha_server_data
